name: Build and Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        java:
          - 21
          - 23
    name: Build and Test
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Build and Run Tests
      run: |
        ./gradlew build
    - name: Upload Coverage Report
      if: contains(matrix.os, 'ubuntu') && contains(matrix.java, '21')
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
